/*
 * Lethean Binary API
 * Functionality to simplify using LTHN
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: contact@lethean.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.lethean.api;

import org.lethean.sdp.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VpnApi
 */
@Ignore
public class VpnApiTest {

    private final VpnApi api = new VpnApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void startLetheandTest() throws ApiException {
        String dataDir = null;
        Boolean version = null;
                api.startLetheand(dataDir, version);
        // TODO: test validations
    }
    
}
